### PR TITLE
updated to PackageAuthorData model

### LINKED ISSUE #122: Deprecation warning Foundry version 10 Build 286 (dd-import version 2.4.0)
Details as in title
- Foundry version 10 Build 286
- dd-import version 2.4.0

When loading the Configuration and Setup page, I get the following warning (yellow bar):
"2 compatibility warnings detected with installed Packages. Consult your console log (F12) for details."

The Log provides these entries:
- [dd-import] The module "dd-import" is using "author" which is deprecated in favor of "authors"
- [dd-import] The module "dd-import" is using "name" which is deprecated in favor of "id"

Thanks for looking into this.

### PR DESCRIPTION
**Pull request by fmefford**
Fixes #122

### CODE REVIEW

**Comment by fmefford** [comment]
Fixes #122

**Comment by brockhaus** [comment]
@fmefford You should add "id" to module.json, too, right?
I just wanted to update this module for v10 depreciation warnings and saw your FR that is handling this partly already. :)

**Comment by fmefford** [comment]
Thanks for the heads up! It looks like id is replacing name in the manifest now, so I went ahead and made that change.

**Comment by brockhaus** [comment]
@fmefford You can have "name" and "id" in the same module.json. That way the file stays compatible with V9 and V10. :)

**Comment by fmefford** [comment]
Ah makes sense. I went ahead and put the old "author" field back in as well as "id". Let me know if there's any issue. Thanks!

**Comment by moo-man** [comment]
The module isn't backwards compatible with V9, so I'll be removing the old authors field. The `name` property is still useful however.

**Pull request merged**
