### PR TITLE
Doors and Walls

### PR DESCRIPTION
**Pull request by m42e**
Reworked the walls and enabled doors

### CODE REVIEW

**Comment by moo-man** [comment]
Wow, awesome! How much has this been tested?

**Comment by m42e** [comment]
I tested it with open walls, rooms, different doors, this one was the most complicated:

image

**Comment by m42e** [comment]
Well I'm not too much into JS, but if you setup the framework for tests, and tell me how to do them, I could add some.

**Comment by moo-man** [comment]
No real framework, just testing various maps with doors. I'll merge this later tonight, awesome work!

**Pull request merged**
